### ISSUE TITLE
`btree_index` in existing database

### ISSUE THREAD

**Issue by tgmichel** [paritytech/parity-db#129]
If I change the configuration for a column from default (`btree_index = false`) to `btree_index = true` and the db already existed, will it automatically index that column when I `open` the db?

**Comment by cheme** [comment]
The db should not open because this is not a supported change (if you look in 'metadata' file in the db repo, all config written should be check on start and an error raised if one of these config is different).

Changing it is not really doable because when `btree_index = false` we do no store the keys, but just the hash of the keys.
Changing in the other direction is doable but not automatic (the migration should be fairly easy to write: read all key value and add them to new column (IIRC I did have some similar process in the admin to rewrite a whole column in a slightly different context).

**Comment by cheme** [comment]
Note that with `btree_index = false`and for the state column, we can access all info (since we store directly hash the `uniform = true` flag indicate that we don't hash the key because we know keys are already 32 byte resulting from a proper hash function).
So we can iterate on all key value in this case, but the iteration need to be part of a migration (the primitives do not support iteration on a live database).

**Comment by cheme** [comment]
Probably changing a bit https://github.com/paritytech/parity-db/blob/3e988a786fe1287d1e404c1993d410bf49c5d146/admin/src/lib.rs#L62 (to force dest to use btree_index = false) should work.
(but only when `uniform = true`)

**Comment by tgmichel** [comment]
Thank you @cheme. For an existing db that was created with the default `btree_index = false` column option, how can I iterate over the keys of a given column?

Also

> Changing in the other direction is doable but not automatic

If that's the case shouldn't `btree_index = true` be the default `Option`?

**Comment by cheme** [comment]
`btree_index = true` is really not focus on performance. So it is slow. The point was initially to cover some needs of polkadot.
With time I see more use of this though, maybe at some point we should do some easy performance gain changes (for instance using fix size indexed table for nodes was way faster but also more code change). Or even propose a different index (I had some experimental radix ones).
But for this feature the initial scope was as small and simple as possible.

**Comment by tgmichel** [comment]
I see thank you. Just to clarify then, if I configured a db with default column options, I understand is not possible to iterate over the keys of a column using the public api?

**Comment by tgmichel** [comment]
Another question, when you mentioned `btree_index = true` is slow, I understand the performance penalty exists on write?

**Comment by cheme** [comment]
Write and read.
By design it will always be slower than `btree_index = false`, I think even if doing all possible optimization.
By choice it is not as efficient as it can be so it's slower than rocksdb for instance.
It wass really a small feature for a restricted use case.

**Comment by tgmichel** [comment]
From a user prespective, I think having the possibility of iterating the keys of a column is a must for most data migrations and it would be a neat addition to the existing api.

You mentioned the case of `uniform` columns, which hold the original unhashed 32 first bytes of the key:

> So we can iterate on all key value in this case, but the iteration need to be part of a migration (the primitives do not support iteration on a live database)

Could you elaborate a bit more on _iteration need to be part of a migration_? If I understood correctly only btree indexed column can provide an iterator.

**Comment by cheme** [comment]
> From a user prespective, I think having the possibility of iterating the keys of a column is a must for most data migrations and it would be a neat addition to the existing api.

yes I hear this a bit (really should have trace the past conversation where the question arise), I also understand that it may be a bit awkward to not be able to retrieve the original keys.
cc @arkpar @Tpt 

> Could you elaborate a bit more on iteration need to be part of a migration? If I understood correctly only btree indexed column can provide an iterator.

Current migration iteration only look at the files and skip all intermediate in memory changes (commit overlay and maybe log overlay), so it requires to flush everything first (and complete running reindexing).
Implementing it to run live should be doable, but the implementation will be likely to be a bit awkward:
- ordering will be random
- due to different layer we would need to keep trace of some returned keys to avoid returning value twice (means may use a bit of memory sometime).
- When column get reindexed, we would need to read from two files (or more) with redundant content
So that's why we currently only have it for migration.
