### ISSUE TITLE
ParityDB Questions

### ISSUE THREAD

**Issue by gakonst** [paritytech/parity-db#162]
Hey folks, few questions which I realize may be sensitive / too detailed so understand if there's no good answer:
1. Is there design document on ParityDB?
2. Have you compared it with other DB choices, like this? https://github.com/ledgerwatch/erigon/wiki/Choice-of-storage-engine
3. How should users think of stability/feature-completeness over time? Where is the project today / where do you expect it to be in 3/6/9/12 months?

**Comment by arkpar** [comment]
> Is there design document on ParityDB?

There's a high level design overview in the [readme](https://github.com/paritytech/parity-db#readme) and some source code level documentation that can be generated with `cargo doc`.

> Have you compared it with other DB choices, like this? https://github.com/ledgerwatch/erigon/wiki/Choice-of-storage-engine

It should be noted that this project is designed to serve the needs of polkadot/substrate blockchain. So most design choices are dictated by substrate design. Substrate currently supports two backends: RocksDB and ParityDB, so we've been mostly comparing these two in the blockchain specific workloads. ParityDb offers better read and write performance at the moment while using slightly more disk space. We've also tested against LMDB at some point, but it turned out to have worse performance than RocksDB for our use case and used too much disk space.

> How should users think of stability/feature-completeness over time? Where is the project today / where do you expect it to be in 3/6/9/12 months?

The current version is considered stable. We'll be switching polkadot/substrate to use it by default soon. There are some additional features and optimizations planned.
