### ISSUE TITLE
Meta Question: How does design consideration translate to implementation details?

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/parity-db#82]
The README in this repo does a great job laying out some of the design considerations for this project, and why these decisions are good for the blockchain.

For Example:

* Small fixed sized keys
* Uniform distribution
* Very few large keys
* Reading more than writing

This repo also does a great job at listing some of the implementation details.

However, not being familiar with database development, how can I better understand which implementation details result in the design considerations?

For example the section `Data structure` notes a unique construction of database tables. Does this help with the fact that most values are small? Or just that values are uniformly distributed?

Not asking for a full explanation of everything, but maybe a off the head mapping of considerations to implementation details.

**Comment by arkpar** [comment]
The database is optimized to be most efficient for storing patricia-merkle trie nodes. It is also used to store other kinds of data, such as block headers or bodies, offchain worker data, etc. But for these extra purposes it is only good enough.

The main implication of the design consideration is that the database can be implented as a probing hash table, and not log-structured merge tree (LSM) as most embedded key-value stores (LevelDB, RocksDB, etc). This is because we don't require key ordering or iteration for trie operations. The benefit here is that read performance in terms of disk reads is constant, rather than log(n) (modulo filesystem overhead).

Here are some additional points:

* 99% of stored trie nodes are less than 32kb in size. Having fixed-sized value tables means that such values only require 2 random disk reads for retrieval. One index lookup and one value table lookup. Values over 32kb may require multiple value table reads, but these are rare.

* Fixed size value tables, as described in "Data structure" helps with minimizing wasted disk space. There's a table for values of size 32, a table of values of size 33, etc. The full list is hardcoded [here](https://github.com/paritytech/parity-db/blob/master/src/column.rs#L65). So for example, if you store a 670 byte value, it won't fit into 662 bucket, but will into 680 bucket, wasting 10 bytes of space. That fact that most values are small allows us to address each value by its index and have a simple mechanism for reusing the space of deleted values without fragmentation and periodic garbage collection. 

* Writes are asynchronous. The `commit` function adds the database transaction to the write queue and returns as quickly as possible. The actual writing happens in the background. This allows the block import pipeline to start executing the next block while the database is still writing changes for the previous block.

**Comment by shawntabrizi** [comment]
thank you very much!
